### ISSUE TITLE
Mudanças no formulário do USUÁRIO

### ISSUE THREAD

**Issue by adrianowy** [thiagonegreiros/sigefi#29]
- [x]  Alterar a label no formulário de FUNÇÃO para PERFIL (ficar claro para a Dna Rose);
- [x]  Adicionar opção para selecionar os dias da semana que faz a a cirurgia e a capacidade de cirurgia por dia.
- [x]  Os campos CPF DO USUÁRIO, CRM DO USUARIO, ESPECIALIDADE, só devem aparecer e ser obrigatório quando o PERFIL for MÉDICOS PRECEPTORES OU Médico Residente;
- [x]  Os campos DIAS DA CIRURGIA e CIRURGIA POR DIA, só devem aparecer e ser obrigatório quando o PERFIL for MÉDICOS PRECEPTORES;
- [x]  Para médicos utilizar 2 nomes de perfil: MÉDICOS PRECEPTORES e MÉDICOS RESIDENTES

**Comment by adrianowy** [comment]
![Image](https://user-images.githubusercontent.com/11649265/216110051-8ef3ad53-d317-4b8e-903c-257126b950dd.png)

**Comment by thiagonegreiros** [comment]
![Image](https://user-images.githubusercontent.com/6574737/216743794-7b855c94-c742-4406-aaee-1447e547e632.png)
