### ISSUE TITLE
Alterar o tamanho do campo CNS

### ISSUE THREAD

**Issue by adrianowy** [thiagonegreiros/sigefi#41]
Alterar o tamanho to campo cns_number pois tem que supotar 15 números.

- no banco antes estava "int4", então eu alterei manualmente para "int8" e aceitou
- essa mudança deve ser aplica no prisma

![Image](https://user-images.githubusercontent.com/11649265/221435604-d15cf9bf-f55c-4e1d-aeac-c7e40a50af63.png)

**Comment by thiagonegreiros** [comment]
Adicinado na branch: [https://github.com/thiagonegreiros/sigefi/tree/feature/sigefi-38](feature/sigefi-38)
