### ISSUE TITLE
Ação para registrar ligação e remover

### ISSUE THREAD

**Issue by adrianowy** [thiagonegreiros/sigefi#5]
- [x] Criar tabela no banco de dados
   > Status,
   > Aih_id,
   > Datetime,
   > Reason (motivo)
   > user_id

- [x] Criar rota de inserir um registro (aih/call/)
- [x] Criar rota listar por aih (/aih/call/:aihId)
- [x] Criar rota para remover o registro (aih/call/:callId)

**Comment by adrianowy** [comment]
@thiagonegreiros , faltou o campo "Datetime", esse campo não é o mesmo do "created_at". O usuário vai registrar dia e hora q ele efetuou a ligação e pode não ser a data e hora atual.

**Comment by thiagonegreiros** [comment]
Adicionado na branch **32-redefinição-da-classificação-de-risco-do-paciente**
