### ISSUE TITLE
Atualizar a lista dos motivos para cancelar a AIH

### ISSUE THREAD

**Issue by adrianowy** [thiagonegreiros/sigefi#60]
- [x] Seguir lista abaixo nos comentários!
  - [x] Atualizar lista em banco de dados
  - [x] Adicionar no type chamado SUSPEND_MOTIVE

![Image](https://user-images.githubusercontent.com/11649265/233704210-253cb0ab-ce60-46c6-bcb1-cba548654ee7.png)

- As opções de CANCELAMENTO devem aparecer para cancelar uma AIH na tela da AIH;
- As opções de suspensão devem aparecer para SUSPENDER uma cirurgia na tela do MAPA.

**Comment by adrianowy** [comment]
<!DOCTYPE html>

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.3.7.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Arial"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>


DESCRICAO | CANCELAMENTO | SUSPENSAO
-- | -- | --
Apresentou problemas clínicos - I.V.A.S. / I.T.U. HIPERTENSÃO / SANGRAMENTO |   | X
Atraso da equipe cirúrgica |   | X
Atraso do anestesista |   | X
Desistiu antes de entrar no bloco cirúrgico | X |  
Equipamento quebrado |   | X
Falha no preparo adequado do paciente |   | X
Falta de anestesista |   | X
Falta de exames complementares – TESTE DE COVID 19 |   | X
Falta de material cirúrgico – instrumental |   | X
Falta de material consignado – OPME E OUTROS |   | X
Falta de material na farmácia |   | X
Falta de OPME |   | X
Falta de reserva sanguínea |   | X
Falta de tipo sanguíneo |   | X
Falta de vaga na enfermaria |   | X
Falta do paciente | X |  
Horário extrapolado de cirurgia anterior |   | X
Insucesso de cirurgia anterior |   | X
Material contaminado |   | X
Mudança de Conduta médica |   | X
Não comparecimento da equipe de cirurgia |   | X
Não solicitou reserva de leito na UTI |   | X
Outros |   |  
Paciente alimentou-se |   | X
Paciente não seguiu as recomendações pré-operatórias |   | X
Substituição da cirurgia por outra de emergência |   | X
Transferiu para outro dia |   | X


</body>

</html>

**Comment by thiagonegreiros** [comment]
![Image](https://github.com/thiagonegreiros/sigefi/assets/6574737/bea901c1-851b-4896-ba1a-b517ece185a9)



![Image](https://github.com/thiagonegreiros/sigefi/assets/6574737/299404cb-b8d6-4904-b665-11218925ab51)

**Comment by thiagonegreiros** [comment]
Também foi arrumado o arquivo de SEED caso seja necessario repopular o banco
