### ISSUE TITLE
Adicionar novos campos no formulário da AIH

### ISSUE THREAD

**Issue by adrianowy** [thiagonegreiros/sigefi#62]
- PROCEDIMENTO SOLICITADO
  - [x] ​PORTE DA CIRURGIA (P, M, G) [usar radio buttom]
  - [x] MATERIAS PERMANENTES + OPME - médico descreve o material; [usar text area]
  - [x] ​ACOMODAÇÃO (CTI, LEITO) [usar radio buttom]
  - [x] ​HEMOCOMPONENTE (sim,não) [usar radio buttom]

@adrianowy , adicionar campos no formulário na aba PROCEDIMENTO SOLICITADO e também olhar a issue #63  para adicionar informações no card do calendário;

@thiagonegreiros , após criar os campos adicionar o nome no comentário

**Comment by adrianowy** [comment]
![Image](https://user-images.githubusercontent.com/11649265/233709409-abef052b-eeaf-48f8-9814-ccf89b609c92.png)

**Comment by thiagonegreiros** [comment]
Deixei esses campos nesse feature **sigefi-62**
