### ISSUE TITLE
Reduzir a quantidade de informações que vem em payload na tela da AIH para melhorar a performance

### ISSUE THREAD

**Issue by adrianowy** [thiagonegreiros/sigefi#64]
- [x] @adrianowy , fazer um filtro que precisa ser mostrado ao carregar a lista da AIH para ficar "mais limpa" (adicionar nos comentários)
   - [x] @thiagonegreiros , aplicar mudança após o @adrianowy definir o novo modelo para retornar os dados;

**Comment by adrianowy** [comment]
@thiagonegreiros , segue abaixo o retorno para a lista da AIH.

```json
{
  "id": "9f9ebe48-1f9a-49d5-9a67-fcb5e4dd5333",
  "classification_risc": "Eletiva não Essencial",
  "status": "ON_HOLD",
  "probable_hospitalization_date": "2023-03-02T22:34:43.793Z",
  "probable_surgery_date": "2023-03-06T22:34:43.793Z",
  "cid": {
        "id": "b33a2ab1-0455-42ee-b7aa-200dd1bb63ce",
        "code": "A00",
        "name": "Cólera",
        "created_at": "2023-02-20T20:53:04.207Z",
        "updated_at": "2023-02-20T20:53:04.336Z"
  },
  "patients": {
    "id": "829100e1-6001-42b1-86eb-2ea4868a1b2e",
    "name": "THIAGO NEGREIROS",
    "medical_record_name": "1234567890",
    "cns_number": 987605403217654,
    "cpf": "24255548234",
    "born_date": "1965-02-12T00:00:00.000Z",
    "genre": "masculino"
    },
  "medicalProcedures": {
    "id": "ed6e5781-3e76-456a-8405-2ab4a000589e",
    "code": "0401010015",
    "name": "CURATIVO GRAU II C/ OU S/ DEBRIDAMENTO",
    "created_at": "2023-02-20T20:53:04.416Z",
    "updated_at": "2023-02-20T20:53:04.432Z"
  },
  "doctorSurgery": {
    "id": "b9652e0c-e1dc-4129-b738-5850c8703307",
    "name": "Medico Cirurgiao",
    "username": "teste_preceptor",
    "crm": "A12345",
    "role": "PRECEPTOR_DOCTOR",
    "doctorSpecialities": {
      "name": "Cardiologia"
    }
  },
  "CallRegister": [
    {
      "id": "0da09066-cd01-453a-85c3-2bc596d3c4eb",
      "reason": "o paciente nao atendeu",
      "status_id": "419f54a7-4781-48f0-a5d5-c50b444b2436",
      "user_id": "e3575c13-6148-4953-81a6-bba85acba95e",
      "aih_id": "9f9ebe48-1f9a-49d5-9a67-fcb5e4dd5333",
      "call_date_time": "2023-02-20T22:36:00.000Z",
      "created_at": "2023-02-20T22:36:45.122Z",
      "updated_at": "2023-02-20T22:36:45.122Z"
    },
    {
      "id": "60f2b93c-ccf3-43e3-9d46-d14593c0c2d4",
      "reason": "o paciente nao atendeu",
      "status_id": "419f54a7-4781-48f0-a5d5-c50b444b2436",
      "user_id": "e3575c13-6148-4953-81a6-bba85acba95e",
      "aih_id": "9f9ebe48-1f9a-49d5-9a67-fcb5e4dd5333",
      "call_date_time": "2023-02-20T22:36:00.000Z",
      "created_at": "2023-02-20T22:37:21.177Z",
      "updated_at": "2023-02-20T22:37:21.178Z"
    }
  ]
}
```

**Comment by thiagonegreiros** [comment]
@adrianowy improvement done.


[
	{
		"id": "402a9179-ef72-47c5-9773-89be5ddad60a",
		"classification_risc": "Urgência Eletiva",
		"status": "ON_HOLD",
		"probable_hospitalization_date": "2023-04-16T03:00:00.000Z",
		"probable_surgery_date": "2023-04-17T03:00:00.000Z",
		"CidAih": [
			{
				"id": "9ed76aac-2e56-4b80-b28f-f29da26b71a7",
				"cid_id": "b33a2ab1-0455-42ee-b7aa-200dd1bb63ce",
				"aih_id": "402a9179-ef72-47c5-9773-89be5ddad60a",
				"cid_type": "PRIMARY",
				"created_at": "2023-04-12T20:27:45.532Z",
				"updated_at": "2023-04-12T20:27:45.533Z",
				"cid": {
					"id": "b33a2ab1-0455-42ee-b7aa-200dd1bb63ce",
					"code": "A00",
					"name": "Cólera"
				}
			},
			{
				"id": "4509099f-70ff-4a76-91ae-7953fca6195b",
				"cid_id": "b33a2ab1-0455-42ee-b7aa-200dd1bb63ce",
				"aih_id": "402a9179-ef72-47c5-9773-89be5ddad60a",
				"cid_type": "SECONDARY",
				"created_at": "2023-04-12T20:27:46.301Z",
				"updated_at": "2023-04-12T20:27:46.301Z",
				"cid": {
					"id": "b33a2ab1-0455-42ee-b7aa-200dd1bb63ce",
					"code": "A00",
					"name": "Cólera"
				}
			},
			{
				"id": "361c3acb-228e-48aa-b4de-d7aae00542b7",
				"cid_id": "b33a2ab1-0455-42ee-b7aa-200dd1bb63ce",
				"aih_id": "402a9179-ef72-47c5-9773-89be5ddad60a",
				"cid_type": "ASSOCIATED",
				"created_at": "2023-04-12T20:27:46.727Z",
				"updated_at": "2023-04-12T20:27:46.727Z",
				"cid": {
					"id": "b33a2ab1-0455-42ee-b7aa-200dd1bb63ce",
					"code": "A00",
					"name": "Cólera"
				}
			}
		],
		"patients": {
			"id": "e6d38785-0704-4bec-b628-c8e1acc3ffc5",
			"name": "ADRIANO DE ABREU WANDERLEY",
			"medical_record_name": "123456123",
			"cns_number": "123456789012345",
			"cpf": "98264060234",
			"born_date": "1991-11-23T00:00:00.000Z",
			"genre": "man"
		},
		"medicalProcedures": {
			"id": "ed6e5781-3e76-456a-8405-2ab4a000589e",
			"code": "0401010015",
			"name": "CURATIVO GRAU II C/ OU S/ DEBRIDAMENTO",
			"created_at": "2023-02-20T20:53:04.416Z",
			"updated_at": "2023-02-20T20:53:04.432Z"
		},
		"doctorSurgery": {
			"id": "5047e393-aa91-4b36-acb9-e355f35decc8",
			"name": "Wesley Pinheiro",
			"username": "wesley.pinheiro",
			"crm": "AB1234",
			"role": "PRECEPTOR_DOCTOR",
			"doctorSpecialities": {
				"name": "Cardiologia"
			}
		},
		"CallRegister": [
			{
				"id": "38bfea81-b2cf-4049-b312-606521c13e89",
				"reason": "11",
				"status_id": "419f54a7-4781-48f0-a5d5-c50b444b2436",
				"user_id": "e3575c13-6148-4953-81a6-bba85acba95e",
				"aih_id": "402a9179-ef72-47c5-9773-89be5ddad60a",
				"call_date_time": "2023-04-18T11:06:00.000Z",
				"created_at": "2023-04-18T10:06:24.627Z",
				"updated_at": "2023-04-18T10:06:24.628Z"
			},
			{
				"id": "e8e4553a-7e62-4f6c-b9bf-77dbb9cb284d",
				"reason": "123123",
				"status_id": "419f54a7-4781-48f0-a5d5-c50b444b2436",
				"user_id": "e3575c13-6148-4953-81a6-bba85acba95e",
				"aih_id": "402a9179-ef72-47c5-9773-89be5ddad60a",
				"call_date_time": "2023-04-19T22:01:00.000Z",
				"created_at": "2023-04-19T21:01:39.524Z",
				"updated_at": "2023-04-19T21:01:39.525Z"
			},
			{
				"id": "6f1dc5f0-3077-471e-ae0e-a14346e099ee",
				"reason": "teste novo adriano",
				"status_id": "01012bf3-bf3c-4638-8c9b-eba57452540f",
				"user_id": "e3575c13-6148-4953-81a6-bba85acba95e",
				"aih_id": "402a9179-ef72-47c5-9773-89be5ddad60a",
				"call_date_time": "2023-04-19T22:34:00.000Z",
				"created_at": "2023-04-19T21:34:22.861Z",
				"updated_at": "2023-04-19T21:34:22.861Z"
			},
			{
				"id": "48838c41-0851-464b-a9b5-fb143036a9e9",
				"reason": "teste novo adriano 2",
				"status_id": "01012bf3-bf3c-4638-8c9b-eba57452540f",
				"user_id": "e3575c13-6148-4953-81a6-bba85acba95e",
				"aih_id": "402a9179-ef72-47c5-9773-89be5ddad60a",
				"call_date_time": "2023-04-19T22:34:00.000Z",
				"created_at": "2023-04-19T21:36:09.065Z",
				"updated_at": "2023-04-19T21:36:09.065Z"
			},
			{
				"id": "1382a0d8-2017-4014-85ba-1be1be97ca44",
				"reason": "adriano",
				"status_id": "ee27c37a-8cd7-4ede-8e55-1a7b21cc53f0",
				"user_id": "e3575c13-6148-4953-81a6-bba85acba95e",
				"aih_id": "402a9179-ef72-47c5-9773-89be5ddad60a",
				"call_date_time": "2023-04-21T10:57:00.000Z",
				"created_at": "2023-04-21T09:57:54.028Z",
				"updated_at": "2023-04-21T09:57:54.029Z"
			}
		]
	},

**Comment by adrianowy** [comment]
@thiagonegreiros , hey man sorry, I forgot to add 2 properties... my bad!

Could you add **created_at** and **updated_at** ?

**Comment by thiagonegreiros** [comment]
@adrianowy already add
